[[fetch]]
files = [
    "ltk/__init__.py",
    "ltk/jquery.py",
    "ltk/pubsub.py",
    "ltk/widgets.py",
    "ltk/logger.py",
    "ltk/ltk.js",
    "ltk/ltk.css",
    "examples/__init__.py",
    "examples/app.py",
    "examples/canvas.py",
    "examples/editor.py",
    "examples/dom.py",
    "examples/inputs.py",
    "examples/tictactoe.py",
    "examples/tictactoe.css",
    "examples/pitch.py",
    "examples/pizza.py",
    "examples/splits.py",
    "examples/styling.py",
    "examples/custom.py",
    "examples/pubsub.py",
    "examples/table.py",
    "examples/svg.py",
    "examples/tutorial.py",
]